name: pre-release

on:
  workflow_dispatch:

jobs:

  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:

      - name: ⬇️ Download artifacts from latest workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success

      - name: 📢 Push to nuget.org
        run: dotnet nuget push lib/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate